version: "3.9"

services:
  app:
    build: .
    container_name: a23davidbc-app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/nutriwise
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    command: npm start

  mongo:
    image: mongo:6.0
    container_name: a23davidbc-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
